apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controllerdeployment.yaml
- controllerregistration.yaml

patches:
- path: patch-controllerdeployment-prow.yaml
- path: patch-imagevector-overwrite-machine-controller-manager-provider-local.yaml
  target:     
    version: v1
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: provider-local
- path: patch-imagevector-overwrite-kms-plugin-provider-local.yaml
  target:     
    version: v1
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: provider-local
