// Code generated by hack/generate-plugin-names.sh. DO NOT EDIT.

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package validation

// allPluginNames contains all supported admission plugin names.
// This is generated from plugin/pkg/plugins.go AllPluginNames() function.
var allPluginNames = []string{
	"NamespaceLifecycle",
	"ResourceReferenceManager",
	"ExtensionValidator",
	"ExtensionLabels",
	"ShootTolerationRestriction",
	"ShootExposureClass",
	"ShootDNS",
	"ShootManagedSeed",
	"ShootNodeLocalDNSEnabledByDefault",
	"ShootDNSRewriting",
	"ShootQuotaValidator",
	"ShootValidator",
	"SeedValidator",
	"SeedMutator",
	"ControllerRegistrationResources",
	"NamespacedCloudProfileValidator",
	"ProjectValidator",
	"DeletionConfirmation",
	"FinalizerRemoval",
	"OpenIDConnectPreset",
	"ClusterOpenIDConnectPreset",
	"CustomVerbAuthorizer",
	"ShootVPAEnabledByDefault",
	"ShootResourceReservation",
	"ManagedSeed",
	"ManagedSeedShoot",
	"Bastion",
	"BackupBucketValidator",
	"MutatingAdmissionPolicy",
	"MutatingAdmissionWebhook",
	"ValidatingAdmissionPolicy",
	"ValidatingAdmissionWebhook",
	"ResourceQuota",
}
