#!/bin/bash

# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGINS_FILE="$REPO_ROOT/plugin/pkg/plugins.go"
OUTPUT_DIR="$REPO_ROOT/pkg/apis/operator/v1alpha1/validation"
OUTPUT_FILE="$OUTPUT_DIR/plugin_names_generated.go"

cat <<EOF > "$OUTPUT_FILE"
// Code generated by hack/generate-plugin-names.sh. DO NOT EDIT.

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package validation

// allPluginNames contains all supported admission plugin names.
// This is generated from plugin/pkg/plugins.go AllPluginNames() function.
var allPluginNames = []string{
EOF

echo "Extracting plugin names from $PLUGINS_FILE..."
while IFS= read -r name; do
    echo "	\"$name\"," >> "$OUTPUT_FILE"
done < <(awk '/func AllPluginNames\(\) \[\]string \{/,/\}/' "$PLUGINS_FILE" | { grep -Eo '//\s*[a-z|A-Z]\w+$' | tr -d '//' | tr -d ' ' || true; })

cat <<EOF >> "$OUTPUT_FILE"
}
EOF
